steps:
- name: 'python'
  entrypoint: 'bash'
  args:
    - -c
    - |
      echo "Running SAST scan..."
      pip install bandit
      bandit -r . -ll -ii --exclude ./cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY
